### PR TITLE
Kibana docs

### PR DESCRIPTION
**Pull request by spalger**
While checking out #2857 I noticed a few things that I thought may or may not be things worth fixing. Rather than try to describe them I figured I would just implement the changes and let you pick through or merge them.

Summary of Changes:
- Change references to "Discover page" to "Discover app". This might have been intentional but I always think of them as separate apps. May or may not want to include this one.
- I thought "vertical bar chart" was a bit vague (which is intentional when describing an entire category of visualizations) so I swapped it out with "histogram"
- recase references to the "time picker" as the "Time Picker"
- modified the "add a time filter" section to be a "update the Time Filter" section
- readded the extensions to several icons, which were not showing up

### CODE REVIEW

**Comment by tbragin** [comment]
- I personally don't think we should talk about "Discover", "Visualize", and "Dashboard" as separate apps in our user-facing documentation. I know we think of them this way internally, and maybe we've implemented them as such, but from a user perspective they are just tabs or pages that enable a single unified workflow. 
- We do have an option "Vertical Bar Chart" in the UI, when a user selects a visualization. If we're referring to clicking on that option, I think we should leave it as-is, unless we want to rename it in the UI.

**Comment by spalger** [comment]
Correct, the Vertical Bar Chart option allows you to create anything that has bars which run vertically. The chart in discover though is not just a vertical bar chart but a chart showing the distribution of documents over time, which is basically the definition of a histogram.

**Comment by tbragin** [comment]
Gotcha. I agree, in that context, it makes sense to change it to "histogram".

**Comment by debadair** [comment]
I went through & incorporated the changes that made sense. As Tanya mentioned, the change from "app" to "page" was deliberate--from the user perspective, it's all one "app". I changed the references in the Discover docs from "time chart" to histogram, and incorporated some of your other changes. Regarding the capitalization of UI elements, I went with "Time Filter, "Time Picker", "Documents table", "Fields list", and "Discover toolbar". The general rule of thumb I'm trying to apply is that if the name occurs in the UI, use name the way it appears in the UI. Otherwise, avoid capitalizing generic labels, such as "list", "table", and "toolbar". If anyone feels strongly about capitalizing them, I'm fine with adopting that style as long as we apply it consistently across the board.

**Pull request closed without merging**
